# opencost-values-cloud.yaml
opencost:
  exporter:
    defaultClusterId: my-gpu-cluster
    extraEnv:
      PROMETHEUS_SERVER_ENDPOINT: "http://kube-prometheus-stack-1741-prometheus.monitoring.svc.cluster.local:9090"
  ui:
    enabled: true

prometheus:
  internal:
    enabled: false
  external:
    enabled: true
    url: http://kube-prometheus-stack-1741-prometheus.monitoring.svc.cluster.local:9090
