# opencost-values-onprem.yaml
opencost:
  exporter:
    defaultClusterId: dgx-a100-cluster
    extraEnv:
      PROMETHEUS_SERVER_ENDPOINT: "http://kube-prometheus-stack-1741-prometheus.monitoring.svc.cluster.local:9090"
      CLOUD_PROVIDER_API_KEY: "AIzaSyD29bGxmHAVEOBYtgd8sYM2gM2ekfxQX4U"
      CLOUD_PROVIDER: "custom"
  ui:
    enabled: true
  
  customPricing:
    enabled: true
    configmapName: opencost-custom-pricing
    configPath: /tmp/custom-config
    createConfigmap: true
    provider: custom
    costModel:
      description: "On-premises NVIDIA GPU pricing"
      CPU: 0.031611      # vCPU-hour
      spotCPU: 0.031611
      RAM: 0.004237      # GB-hour
      spotRAM: 0.004237
      GPU: 0.95          # NVIDIA GPU-hour - CHANGE THIS for your NVIDIA GPU
      storage: 0.04      # GB-month
      zoneNetworkEgress: 0.01
      regionNetworkEgress: 0.01
      internetNetworkEgress: 0.12

prometheus:
  internal:
    enabled: false
  external:
    enabled: true
    url: http://kube-prometheus-stack-1741-prometheus.monitoring.svc.cluster.local:9090
