# OpenCost values for Cloud Environments (AWS, GCP, Azure)
# Automatic cloud pricing detection - no custom pricing needed!

opencost:
  exporter:
    defaultClusterId: my-gpu-cluster
    # Cloud provider auto-detection - OpenCost automatically fetches pricing!
    # No CLOUD_PROVIDER setting needed - it auto-detects AWS, GCP, or Azure
  ui:
    enabled: true

prometheus:
  internal:
    enabled: true
    servicemonitors:
      enabled: true
  external:
    enabled: false

