---
# ServiceMonitor for DCGM metrics
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nvidia-dcgm-exporter
  namespace: monitoring
  labels:
    app: nvidia-dcgm-exporter
    release: kube-prometheus-stack-1741
spec:
  selector:
    matchLabels:
      app: nvidia-dcgm-exporter
  namespaceSelector:
    matchNames:
      - nvidia-gpu-operator
  endpoints:
    - port: gpu-metrics
      interval: 30s
      path: /metrics
---
# NodePort service for OpenCost UI/API access
apiVersion: v1
kind: Service
metadata:
  name: opencost-ui
  namespace: opencost
  labels:
    app: opencost
    app.kubernetes.io/name: opencost
spec:
  type: NodePort
  ports:
    - name: http-ui
      port: 9090
      targetPort: 9090
      nodePort: 30091
    - name: http-api
      port: 9003
      targetPort: 9003
      nodePort: 30031
  selector:
    app.kubernetes.io/name: opencost
